# Data Preparation

In this notebook, I will explore the steps carried down to add and rearrange fields in the given dataset.

Notable preprocessing steps:
- Insert 'Region' field to the dataset
- Pivot set of columns into rows
- Remove unwanted fields
- Clear errors in the 'Local district' column such as removing the leading spaces and correcting spelling mistakes

In [1]:
#necessary libraries
import pandas as pd
import os

# 1. Dataset - Occupation ethnic age gender

In [2]:
#directory path
original_data_path = os.path.join(os.getcwd(), 'original data')
transformed_data_path = os.path.join(os.getcwd(), 'transformed data')

In [3]:
#store the current directory as pwd
pwd = os.getcwd()

In [4]:
os.chdir(original_data_path) #change the directory
df1 = pd.read_excel("Occupation ethnic age gender.xlsx") #load the dataset
os.chdir(pwd) #change the directory back to pwd

In [5]:
#remove 'All' column
df1.drop('All', inplace=True, axis=1)

In [6]:
#check for null values
df1.isnull().any()

Local district                                      False
Gender                                              False
Ethnic                                              False
Age                                                 False
Managers, directors and senior officials            False
Professional occupations                            False
Associate professional and technical occupations    False
Administrative and secretarial occupations          False
Skilled trades occupations                          False
Caring, leisure and other service occupations       False
Sales and customer service occupations              False
Process, plant and machine operatives               False
Elementary occupations                              False
dtype: bool

In [7]:
df1.head()

,Local district,Gender,Ethnic,Age,"Managers, directors and senior officials",Professional occupations,Associate professional and technical occupations,Administrative and secretarial occupations,Skilled trades occupations,"Caring, leisure and other service occupations",Sales and customer service occupations,"Process, plant and machine operatives",Elementary occupations
0,Darlington,Male,White,16 to 24,96,153,370,243,602,138,434,190,658
1,County Durham,Male,White,16 to 24,426,779,1442,796,3268,611,2019,1533,3275
2,Hartlepool,Male,White,16 to 24,51,120,265,105,707,123,333,271,518
3,Middlesbrough,Male,White,16 to 24,88,231,381,184,829,227,657,313,879
4,Northumberland,Male,White,16 to 24,293,399,1118,397,2129,397,1222,683,1954

In [7]:
#preprocessing steps
df1['Local district'] = df1['Local district'].str.strip() #remove the leading spaces from the Local district column
df1['Ethnic'] = df1['Ethnic'].str.strip() #remove the leading spaces from the Ethnic column
df1['Gender'] = df1['Gender'].str.strip() #remove the leading spaces from the Gender column
df1['Age'] = df1['Age'].str.strip() #remove the leading spaces from the Age column

In [8]:
#Pivot the columns from the slice of [4:] into rows
df1 = (df1.set_index(["Local district","Gender","Ethnic","Age"])
         .stack()
         .reset_index(name='Total people with occupations')
         .rename(columns={'level_4':'Occupation'}))

In [9]:
#distinguish Local district in df1 using regions
region = {'County Durham': 'North East',
 'Darlington': 'North East',
 'Hartlepool': 'North East',
 'Middlesbrough': 'North East',
 'Northumberland': 'North East',
 'Redcar and Cleveland': 'North East',
 'Stockton-on-Tees': 'North East',
 'Gateshead': 'North East',
 'Newcastle upon Tyne': 'North East',
 'North Tyneside': 'North East',
 'South Tyneside': 'North East',
 'Sunderland': 'North East',
 'Blackburn with Darwen': 'North West',
 'Blackpool': 'North West',
 'Cheshire East': 'North West',
 'Cheshire West and Chester': 'North West',
 'Halton': 'North West',
 'Warrington': 'North West',
 'Allerdale': 'North West',
 'Barrow-in-Furness': 'North West',
 'Carlisle': 'North West',
 'Copeland': 'North West',
 'Eden': 'North West',
 'South Lakeland': 'North West',
 'Bolton': 'North West',
 'Bury': 'North West',
 'Manchester': 'North West',
 'Oldham': 'North West',
 'Rochdale': 'North West',
 'Salford': 'North West',
 'Stockport': 'North West',
 'Tameside': 'North West',
 'Trafford': 'North West',
 'Wigan': 'North West',
 'Burnley': 'North West',
 'Chorley': 'North West',
 'Fylde': 'North West',
 'Hyndburn': 'North West',
 'Lancaster': 'North West',
 'Pendle': 'North West',
 'Preston': 'North West',
 'Ribble Valley': 'North West',
 'Rossendale': 'North West',
 'South Ribble': 'North West',
 'West Lancashire': 'North West',
 'Wyre': 'North West',
 'Knowsley': 'North West',
 'Liverpool': 'North West',
 'Sefton': 'North West',
 'St. Helens': 'North West',
 'Wirral': 'North West',
 'East Riding of Yorkshire': 'Yorkshire and The Humber',
 'Kingston upon Hull, City of': 'Yorkshire and The Humber',
 'North East Lincolnshire': 'Yorkshire and The Humber',
 'North Lincolnshire': 'Yorkshire and The Humber',
 'York': 'Yorkshire and The Humber',
 'Craven': 'Yorkshire and The Humber',
 'Hambleton': 'Yorkshire and The Humber',
 'Harrogate': 'Yorkshire and The Humber',
 'Richmondshire': 'Yorkshire and The Humber',
 'Ryedale': 'Yorkshire and The Humber',
 'Scarborough': 'Yorkshire and The Humber',
 'Selby': 'Yorkshire and The Humber',
 'Barnsley': 'Yorkshire and The Humber',
 'Doncaster': 'Yorkshire and The Humber',
 'Rotherham': 'Yorkshire and The Humber',
 'Sheffield': 'Yorkshire and The Humber',
 'Bradford': 'Yorkshire and The Humber',
 'Calderdale': 'Yorkshire and The Humber',
 'Kirklees': 'Yorkshire and The Humber',
 'Leeds': 'Yorkshire and The Humber',
 'Wakefield': 'Yorkshire and The Humber',
 'Derby': 'East Midlands',
 'Leicester': 'East Midlands',
 'Nottingham': 'East Midlands',
 'Rutland': 'East Midlands',
 'Amber Valley': 'East Midlands',
 'Bolsover': 'East Midlands',
 'Chesterfield': 'East Midlands',
 'Derbyshire Dales': 'East Midlands',
 'Erewash': 'East Midlands',
 'High Peak': 'East Midlands',
 'North East Derbyshire': 'East Midlands',
 'South Derbyshire': 'East Midlands',
 'Blaby': 'East Midlands',
 'Charnwood': 'East Midlands',
 'Harborough': 'East Midlands',
 'Hinckley and Bosworth': 'East Midlands',
 'Melton': 'East Midlands',
 'North West Leicestershire': 'East Midlands',
 'Oadby and Wigston': 'East Midlands',
 'Boston': 'East Midlands',
 'East Lindsey': 'East Midlands',
 'Lincoln': 'East Midlands',
 'North Kesteven': 'East Midlands',
 'South Holland': 'East Midlands',
 'South Kesteven': 'East Midlands',
 'West Lindsey': 'East Midlands',
 'Corby': 'East Midlands',
 'Daventry': 'East Midlands',
 'East Northamptonshire': 'East Midlands',
 'Kettering': 'East Midlands',
 'Northampton': 'East Midlands',
 'South Northamptonshire': 'East Midlands',
 'Wellingborough': 'East Midlands',
 'Ashfield': 'East Midlands',
 'Bassetlaw': 'East Midlands',
 'Broxtowe': 'East Midlands',
 'Gedling': 'East Midlands',
 'Mansfield': 'East Midlands',
 'Newark and Sherwood': 'East Midlands',
 'Rushcliffe': 'East Midlands',
 'Herefordshire, County of': 'West Midlands',
 'Shropshire': 'West Midlands',
 'Stoke-on-Trent': 'West Midlands',
 'Telford and Wrekin': 'West Midlands',
 'Cannock Chase': 'West Midlands',
 'East Staffordshire': 'West Midlands',
 'Lichfield': 'West Midlands',
 'Newcastle-under-Lyme': 'West Midlands',
 'South Staffordshire': 'West Midlands',
 'Stafford': 'West Midlands',
 'Staffordshire Moorlands': 'West Midlands',
 'Tamworth': 'West Midlands',
 'North Warwickshire': 'West Midlands',
 'Nuneaton and Bedworth': 'West Midlands',
 'Rugby': 'West Midlands',
 'Stratford-on-Avon': 'West Midlands',
 'Warwick': 'West Midlands',
 'Birmingham': 'West Midlands',
 'Coventry': 'West Midlands',
 'Dudley': 'West Midlands',
 'Sandwell': 'West Midlands',
 'Solihull': 'West Midlands',
 'Walsall': 'West Midlands',
 'Wolverhampton': 'West Midlands',
 'Bromsgrove': 'West Midlands',
 'Malvern Hills': 'West Midlands',
 'Redditch': 'West Midlands',
 'Worcester': 'West Midlands',
 'Wychavon': 'West Midlands',
 'Wyre Forest': 'West Midlands',
 'Bedford': 'East',
 'Central Bedfordshire': 'East',
 'Luton': 'East',
 'Peterborough': 'East',
 'Southend-on-Sea': 'East',
 'Thurrock': 'East',
 'Cambridge': 'East',
 'East Cambridgeshire': 'East',
 'Fenland': 'East',
 'Huntingdonshire': 'East',
 'South Cambridgeshire': 'East',
 'Basildon': 'East',
 'Braintree': 'East',
 'Brentwood': 'East',
 'Castle Point': 'East',
 'Chelmsford': 'East',
 'Colchester': 'East',
 'Epping Forest': 'East',
 'Harlow': 'East',
 'Maldon': 'East',
 'Rochford': 'East',
 'Tendring': 'East',
 'Uttlesford': 'East',
 'Broxbourne': 'East',
 'Dacorum': 'East',
 'East Hertfordshire': 'East',
 'Hertsmere': 'East',
 'North Hertfordshire': 'East',
 'St Albans': 'East',
 'Stevenage': 'East',
 'Three Rivers': 'East',
 'Watford': 'East',
 'Welwyn Hatfield': 'East',
 'Breckland': 'East',
 'Broadland': 'East',
 'Great Yarmouth': 'East',
 'King’s Lynn and West Norfolk': 'East',
 'North Norfolk': 'East',
 'Norwich': 'East',
 'South Norfolk': 'East',
 'Babergh': 'East',
 'Forest Heath': 'East',
 'Ipswich': 'East',
 'Mid Suffolk': 'East',
 'St Edmundsbury': 'East',
 'Suffolk Coastal': 'East',
 'Waveney': 'East',
 'Camden': 'London',
 'City of London': 'London',
 'Hackney': 'London',
 'Hammersmith and Fulham': 'London',
 'Haringey': 'London',
 'Islington': 'London',
 'Kensington and Chelsea': 'London',
 'Lambeth': 'London',
 'Lewisham': 'London',
 'Newham': 'London',
 'Southwark': 'London',
 'Tower Hamlets': 'London',
 'Wandsworth': 'London',
 'Westminster': 'London',
 'Barking and Dagenham': 'London',
 'Barnet': 'London',
 'Bexley': 'London',
 'Brent': 'London',
 'Bromley': 'London',
 'Croydon': 'London',
 'Ealing': 'London',
 'Enfield': 'London',
 'Greenwich': 'London',
 'Harrow': 'London',
 'Havering': 'London',
 'Hillingdon': 'London',
 'Hounslow': 'London',
 'Kingston upon Thames': 'London',
 'Merton': 'London',
 'Redbridge': 'London',
 'Richmond upon Thames': 'London',
 'Sutton': 'London',
 'Waltham Forest': 'London',
 'Bracknell Forest': 'South East',
 'Brighton and Hove': 'South East',
 'Isle of Wight': 'South East',
 'Medway': 'South East',
 'Milton Keynes': 'South East',
 'Portsmouth': 'South East',
 'Reading': 'South East',
 'Slough': 'South East',
 'Southampton': 'South East',
 'West Berkshire': 'South East',
 'Windsor and Maidenhead': 'South East',
 'Wokingham': 'South East',
 'Aylesbury Vale': 'South East',
 'Chiltern': 'South East',
 'South Bucks': 'South East',
 'Wycombe': 'South East',
 'Eastbourne': 'South East',
 'Hastings': 'South East',
 'Lewes': 'South East',
 'Rother': 'South East',
 'Wealden': 'South East',
 'Basingstoke and Deane': 'South East',
 'East Hampshire': 'South East',
 'Eastleigh': 'South East',
 'Fareham': 'South East',
 'Gosport': 'South East',
 'Hart': 'South East',
 'Havant': 'South East',
 'New Forest': 'South East',
 'Rushmoor': 'South East',
 'Test Valley': 'South East',
 'Winchester': 'South East',
 'Ashford': 'South East',
 'Canterbury': 'South East',
 'Dartford': 'South East',
 'Dover': 'South East',
 'Gravesham': 'South East',
 'Maidstone': 'South East',
 'Sevenoaks': 'South East',
 'Shepway': 'South East',
 'Swale': 'South East',
 'Thanet': 'South East',
 'Tonbridge and Malling': 'South East',
 'Tunbridge Wells': 'South East',
 'Cherwell': 'South East',
 'Oxford': 'South East',
 'South Oxfordshire': 'South East',
 'Vale of White Horse': 'South East',
 'West Oxfordshire': 'South East',
 'Elmbridge': 'South East',
 'Epsom and Ewell': 'South East',
 'Guildford': 'South East',
 'Mole Valley': 'South East',
 'Reigate and Banstead': 'South East',
 'Runnymede': 'South East',
 'Spelthorne': 'South East',
 'Surrey Heath': 'South East',
 'Tandridge': 'South East',
 'Waverley': 'South East',
 'Woking': 'South East',
 'Adur': 'South East',
 'Arun': 'South East',
 'Chichester': 'South East',
 'Crawley': 'South East',
 'Horsham': 'South East',
 'Mid Sussex': 'South East',
 'Worthing': 'South East',
 'Bath and North East Somerset': 'South West',
 'Bournemouth': 'South West',
 'Bristol, City of': 'South West',
 'Cornwall': 'South West',
 'Isles of Scilly': 'South West',
 'North Somerset': 'South West',
 'Plymouth': 'South West',
 'Poole': 'South West',
 'South Gloucestershire': 'South West',
 'Swindon': 'South West',
 'Torbay': 'South West',
 'Wiltshire': 'South West',
 'East Devon': 'South West',
 'Exeter': 'South West',
 'Mid Devon': 'South West',
 'North Devon': 'South West',
 'South Hams': 'South West',
 'Teignbridge': 'South West',
 'Torridge': 'South West',
 'West Devon': 'South West',
 'Christchurch': 'South West',
 'East Dorset': 'South West',
 'North Dorset': 'South West',
 'Purbeck': 'South West',
 'West Dorset': 'South West',
 'Weymouth and Portland': 'South West',
 'Cheltenham': 'South West',
 'Cotswold': 'South West',
 'Forest of Dean': 'South West',
 'Gloucester': 'South West',
 'Stroud': 'South West',
 'Tewkesbury': 'South West',
 'Mendip': 'South West',
 'Sedgemoor': 'South West',
 'South Somerset': 'South West',
 'Taunton Deane': 'South West',
 'West Somerset': 'South West',
 'Isle of Anglesey': 'Wales',
 'Gwynedd': 'Wales',
 'Conwy': 'Wales',
 'Denbighshire': 'Wales',
 'Flintshire': 'Wales',
 'Wrexham': 'Wales',
 'Powys': 'Wales',
 'Ceredigion': 'Wales',
 'Pembrokeshire': 'Wales',
 'Carmarthenshire': 'Wales',
 'Swansea': 'Wales',
 'Neath Port Talbot': 'Wales',
 'Bridgend': 'Wales',
 'Vale of Glamorgan': 'Wales',
 'Cardiff': 'Wales',
 'Rhondda Cynon Taf': 'Wales',
 'Merthyr Tydfil': 'Wales',
 'Caerphilly': 'Wales',
 'Blaenau Gwent': 'Wales',
 'Torfaen': 'Wales',
 'Monmouthshire': 'Wales',
 'Newport': 'Wales',
 "King’s Lynn and West Norfolk":'East',
 'Shepway':'South West'}

In [10]:
#create region using region dictionary mapping Local district
df1["Region"] = df1["Local district"].map(region)

In [11]:
#check for any null values
null = df1[df1.isnull().any(axis=1)]
null

,Local district,Gender,Ethnic,Age,Occupation,Total people with occupations,Region
1602,King's Lynn and West Norfolk,Male,White,16 to 24,"Managers, directors and senior officials",178,NaN
1603,King's Lynn and West Norfolk,Male,White,16 to 24,Professional occupations,150,NaN
1604,King's Lynn and West Norfolk,Male,White,16 to 24,Associate professional and technical occupations,687,NaN
1605,King's Lynn and West Norfolk,Male,White,16 to 24,Administrative and secretarial occupations,203,NaN
1606,King's Lynn and West Norfolk,Male,White,16 to 24,Skilled trades occupations,1135,NaN
...,...,...,...,...,...,...,...
124501,Folkestone and Hythe,Female,Other,65+,Skilled trades occupations,0,NaN
124502,Folkestone and Hythe,Female,Other,65+,"Caring, leisure and other service occupations",1,NaN
124503,Folkestone and Hythe,Female,Other,65+,Sales and customer service occupations,0,NaN
124504,Folkestone and Hythe,Female,Other,65+,"Process, plant and machine operatives",0,NaN
124505,Folkestone and Hythe,Female,Other,65+,Elementary occupations,1,NaN

In [12]:
set(null["Local district"])

{'Folkestone and Hythe', "King's Lynn and West Norfolk"}

In [13]:
#replace Folkestone and Hythe to Shepway
df1['Local district'] = df1['Local district'].str.replace('Folkestone and Hythe','Shepway')
df1['Local district'] = df1['Local district'].str.replace("King's Lynn and West Norfolk","King’s Lynn and West Norfolk")

In [14]:
#create region using region dictionary mapping Local district
df1["Region"] = df1["Local district"].map(region)

In [15]:
null = df1[df1.isnull().any(axis=1)]
null

Empty DataFrame
Columns: [Local district, Gender, Ethnic, Age, Occupation, Total people with occupations, Region]
Index: []

In [16]:
#rearrange the columns
df1 = df1[["Local district", "Region", "Ethnic", "Gender", "Age", "Occupation", "Total people with occupations"]]

In [17]:
df1.head()

,Local district,Region,Ethnic,Gender,Age,Occupation,Total people with occupations
0,Darlington,North East,White,Male,16 to 24,"Managers, directors and senior officials",96
1,Darlington,North East,White,Male,16 to 24,Professional occupations,153
2,Darlington,North East,White,Male,16 to 24,Associate professional and technical occupations,370
3,Darlington,North East,White,Male,16 to 24,Administrative and secretarial occupations,243
4,Darlington,North East,White,Male,16 to 24,Skilled trades occupations,602

In [18]:
#save as excel file
os.chdir(transformed_data_path)
df1.to_excel("occupation ethnic age gender.xlsx")
os.chdir(pwd)

In [19]:
df1.isnull().any()

Local district                   False
Region                           False
Ethnic                           False
Gender                           False
Age                              False
Occupation                       False
Total people with occupations    False
dtype: bool

#strip all the leading spaces
df2['Area code'] = df2['Area code'].str.strip()
df2['Area'] = df2['Area'].str.strip()
df2['Area'] = df2['Area'].str.replace("King's Lynn and West Norfolk","King’s Lynn and West Norfolk")
df2['Area'] = df2['Area'].str.replace('Rhondda Cynon Taff','Rhondda Cynon Taf')
df2['Area'] = df2['Area'].str.replace('Vale of Glamorgan','The Vale of Glamorgan')
df2['Area'] = df2['Area'].str.replace('Folkestone and Hythe','Shepway')

#strip all the leading spaces
df3['Area code'] = df3['Area code'].str.strip()
df3['Area'] = df3['Area'].str.strip()
df3['Area'] = df3['Area'].str.replace("King's Lynn and West Norfolk","King’s Lynn and West Norfolk")
df3['Area'] = df3['Area'].str.replace('Rhondda Cynon Taff','Rhondda Cynon Taf')
df3['Area'] = df3['Area'].str.replace('Vale of Glamorgan','The Vale of Glamorgan')
df3['Area'] = df3['Area'].str.replace('Folkestone and Hythe','Shepway')

# 2. Occupation by economic activity by gender

In [20]:
os.chdir(original_data_path) #change the directory
df2 = pd.read_excel("Occupation by economic activity by gender.xlsx") #load the dataset
os.chdir(pwd) #change the directory back to pwd

In [21]:
#remove 'All' column
df2.drop('All', inplace=True, axis=1)

In [22]:
#check for null values
df2.isnull().any()

Local district                                      False
Managers, directors and senior officials            False
Professional occupations                            False
Associate professional and technical occupations    False
Administrative and secretarial occupations          False
Skilled trades occupations                          False
Caring, leisure and other service occupations       False
Sales and customer service occupations              False
Process, plant and machine operatives               False
Elementary occupations                              False
Gender                                              False
Employment                                          False
dtype: bool

In [23]:
df2.head()

,Local district,"Managers, directors and senior officials",Professional occupations,Associate professional and technical occupations,Administrative and secretarial occupations,Skilled trades occupations,"Caring, leisure and other service occupations",Sales and customer service occupations,"Process, plant and machine operatives",Elementary occupations,Gender,Employment
0,Darlington,2204,3102,3033,1299,3639,750,1621,2783,2913,Male,Employee
1,County Durham,9398,13167,12676,5255,18524,4001,5581,18138,13800,Male,Employee
2,Hartlepool,1373,1909,2194,651,3635,638,914,3113,2278,Male,Employee
3,Middlesbrough,1799,2824,2723,1197,4539,1179,1931,4074,3977,Male,Employee
4,Northumberland,6927,8539,8721,3243,10593,2722,3589,8856,7726,Male,Employee

In [24]:
#preprocessing steps
df2['Local district'] = df2['Local district'].str.strip() #remove the leading spaces from the Local district column
df2['Employment'] = df2['Employment'].str.strip() #remove the leading spaces from the Employment column
df2['Gender'] = df2['Gender'].str.strip() #remove the leading spaces from the Gender column

In [25]:
#Pivot the columns into rows
df2 = (df2.set_index(["Local district","Gender","Employment"])
         .stack()
         .reset_index(name='Total people with occupations')
         .rename(columns={'level_3':'Occupation'}))

In [26]:
#create region using region dictionary mapping Local district
df2["Region"] = df2["Local district"].map(region)

In [27]:
#check for any null values
null = df2[df2.isnull().any(axis=1)]
null

,Local district,Gender,Employment,Occupation,Total people with occupations,Region
1602,King's Lynn and West Norfolk,Male,Employee,"Managers, directors and senior officials",3350,NaN
1603,King's Lynn and West Norfolk,Male,Employee,Professional occupations,2939,NaN
1604,King's Lynn and West Norfolk,Male,Employee,Associate professional and technical occupations,3971,NaN
1605,King's Lynn and West Norfolk,Male,Employee,Administrative and secretarial occupations,1111,NaN
1606,King's Lynn and West Norfolk,Male,Employee,Skilled trades occupations,5385,NaN
...,...,...,...,...,...,...
11749,Folkestone and Hythe,Female,Self-Employed,Skilled trades occupations,225,NaN
11750,Folkestone and Hythe,Female,Self-Employed,"Caring, leisure and other service occupations",449,NaN
11751,Folkestone and Hythe,Female,Self-Employed,Sales and customer service occupations,67,NaN
11752,Folkestone and Hythe,Female,Self-Employed,"Process, plant and machine operatives",51,NaN
11753,Folkestone and Hythe,Female,Self-Employed,Elementary occupations,174,NaN

In [28]:
set(null["Local district"])

{'Folkestone and Hythe', "King's Lynn and West Norfolk"}

In [29]:
#replace Folkestone and Hythe to Shepway
df2['Local district'] = df2['Local district'].str.replace('Folkestone and Hythe','Shepway')
df2['Local district'] = df2['Local district'].str.replace("King's Lynn and West Norfolk","King’s Lynn and West Norfolk")

In [30]:
#create region using region dictionary mapping Local district
df2["Region"] = df2["Local district"].map(region)

In [31]:
#check for any null values
null = df2[df2.isnull().any(axis=1)]
null

Empty DataFrame
Columns: [Local district, Gender, Employment, Occupation, Total people with occupations, Region]
Index: []

In [32]:
#rearrange the columns
df2 = df2[["Local district", "Region", "Employment", "Gender", "Occupation", "Total people with occupations"]]

In [33]:
#save as excel file
os.chdir(transformed_data_path)
with pd.ExcelWriter("occupation ethnic age gender.xlsx", mode='a', engine="openpyxl") as writer:
    df2.to_excel(writer, sheet_name='occ ea gender')
os.chdir(pwd)

# 3. Occupation by hours worked by gender

In [34]:
os.chdir(original_data_path) #change the directory
df3 = pd.read_csv("Occupation by hours worked by gender.csv") #load the dataset
os.chdir(pwd) #change the directory back to pwd

In [35]:
#remove 'All' column
df3.drop('All', inplace=True, axis=1)

In [36]:
#check for null values
df3.isnull().any()

Local district                                      False
Gender                                              False
Hours worked                                        False
Managers, directors and senior officials            False
Professional occupations                            False
Associate professional and technical occupations    False
Administrative and secretarial occupations          False
Skilled trades occupations                          False
Caring, leisure and other service occupations       False
Sales and customer service occupations              False
Process, plant and machine operatives               False
Elementary occupations                              False
dtype: bool

In [37]:
df3.head()

,Local district,Gender,Hours worked,"Managers, directors and senior officials",Professional occupations,Associate professional and technical occupations,Administrative and secretarial occupations,Skilled trades occupations,"Caring, leisure and other service occupations",Sales and customer service occupations,"Process, plant and machine operatives",Elementary occupations
0,Darlington,Male,Part-time: 15 hours or less,74,123,147,56,150,53,214,112,365
1,County Durham,Male,Part-time: 15 hours or less,338,826,646,257,736,317,841,596,1599
2,Hartlepool,Male,Part-time: 15 hours or less,62,76,101,34,124,43,129,109,267
3,Middlesbrough,Male,Part-time: 15 hours or less,88,153,170,57,205,111,370,186,565
4,Northumberland,Male,Part-time: 15 hours or less,337,521,494,161,510,224,505,335,988

In [38]:
#preprocessing steps
df3['Local district'] = df3['Local district'].str.strip() #remove the leading spaces from the Local district column
df3['Gender'] = df3['Gender'].str.strip() #remove the leading spaces from the Gender column
df3['Hours worked'] = df3['Hours worked'].str.strip() #remove the leading spaces from the Hours worked column

In [39]:
#Pivot the columns into rows
df3 = (df3.set_index(["Local district","Gender","Hours worked"])
         .stack()
         .reset_index(name='Total people with occupations')
         .rename(columns={'level_3':'Occupation'}))

In [40]:
#create region using region dictionary mapping Local district
df3["Region"] = df3["Local district"].map(region)

In [41]:
#check for any null values
null = df3[df3.isnull().any(axis=1)]
null

,Local district,Gender,Hours worked,Occupation,Total people with occupations,Region
1602,King's Lynn and West Norfolk,Male,Part-time: 15 hours or less,"Managers, directors and senior officials",151,NaN
1603,King's Lynn and West Norfolk,Male,Part-time: 15 hours or less,Professional occupations,204,NaN
1604,King's Lynn and West Norfolk,Male,Part-time: 15 hours or less,Associate professional and technical occupations,188,NaN
1605,King's Lynn and West Norfolk,Male,Part-time: 15 hours or less,Administrative and secretarial occupations,79,NaN
1606,King's Lynn and West Norfolk,Male,Part-time: 15 hours or less,Skilled trades occupations,304,NaN
...,...,...,...,...,...,...
24277,Folkestone and Hythe,Female,Full-time: 49 or more hours,Skilled trades occupations,71,NaN
24278,Folkestone and Hythe,Female,Full-time: 49 or more hours,"Caring, leisure and other service occupations",265,NaN
24279,Folkestone and Hythe,Female,Full-time: 49 or more hours,Sales and customer service occupations,31,NaN
24280,Folkestone and Hythe,Female,Full-time: 49 or more hours,"Process, plant and machine operatives",15,NaN
24281,Folkestone and Hythe,Female,Full-time: 49 or more hours,Elementary occupations,34,NaN

In [42]:
set(null["Local district"])

{'Folkestone and Hythe', "King's Lynn and West Norfolk"}

In [43]:
#replace Folkestone and Hythe to Shepway
df3['Local district'] = df3['Local district'].str.replace('Folkestone and Hythe','Shepway')
df3['Local district'] = df3['Local district'].str.replace("King's Lynn and West Norfolk","King’s Lynn and West Norfolk")

In [44]:
#create region using region dictionary mapping Local district
df3["Region"] = df3["Local district"].map(region)

In [45]:
#check for any null values
null = df3[df3.isnull().any(axis=1)]
null

Empty DataFrame
Columns: [Local district, Gender, Hours worked, Occupation, Total people with occupations, Region]
Index: []

In [46]:
#rearrange the columns
df3 = df3[["Local district", "Region", "Hours worked", "Gender", "Occupation", "Total people with occupations"]]

In [47]:
#save as excel file
os.chdir(transformed_data_path)
with pd.ExcelWriter("occupation ethnic age gender.xlsx", mode='a', engine="openpyxl") as writer:
    df3.to_excel(writer, sheet_name='occ hrs gender')
os.chdir(pwd)

# 4. Occupation by highest level of qualification by age

In [48]:
os.chdir(original_data_path) #change the directory
df4 = pd.read_csv("Occupation by highest level of qualification by age.csv") #load the dataset
os.chdir(pwd) #change the directory back to pwd

In [49]:
#remove 'All' column
df4.drop('All', inplace=True, axis=1)

In [50]:
#check for null values
df4.isnull().any()

Local district                                      False
Managers, directors and senior officials            False
Professional occupations                            False
Associate professional and technical occupations    False
Administrative and secretarial occupations          False
Skilled trades occupations                          False
Caring, leisure and other service occupations       False
Sales and customer service occupations              False
Process, plant and machine operatives               False
Elementary occupations                              False
Age                                                 False
Qualification                                       False
dtype: bool

In [51]:
df4.head()

,Local district,"Managers, directors and senior officials",Professional occupations,Associate professional and technical occupations,Administrative and secretarial occupations,Skilled trades occupations,"Caring, leisure and other service occupations",Sales and customer service occupations,"Process, plant and machine operatives",Elementary occupations,Age,Qualification
0,Hartlepool,3,4,9,4,38,22,49,25,67,16-24,No qualifications
1,Middlesbrough,10,5,22,18,68,49,99,59,174,16-24,No qualifications
2,Redcar and Cleveland,9,6,8,14,60,34,62,48,116,16-24,No qualifications
3,Stockton-on-Tees,23,8,26,19,66,49,94,54,189,16-24,No qualifications
4,Darlington,17,2,15,11,43,33,63,36,119,16-24,No qualifications

In [52]:
#preprocessing steps
df4['Local district'] = df4['Local district'].str.strip() #remove the leading spaces from the Local district column
df4['Age'] = df4['Age'].str.strip() #remove the leading spaces from the Age column
df4['Qualification'] = df4['Qualification'].str.strip() #remove the leading spaces from the 'Qualification'column

In [53]:
#Pivot the columns into rows
df4 = (df4.set_index(["Local district","Age","Qualification"])
         .stack()
         .reset_index(name='Total people with occupations')
         .rename(columns={'level_3':'Occupation'}))

In [54]:
#create region using region dictionary mapping Local district
df4["Region"] = df4["Local district"].map(region)

In [55]:
#check for any null values
null = df4[df4.isnull().any(axis=1)]
null

,Local district,Age,Qualification,Occupation,Total people with occupations,Region
1602,King's Lynn and West Norfolk,16-24,No qualifications,"Managers, directors and senior officials",17,NaN
1603,King's Lynn and West Norfolk,16-24,No qualifications,Professional occupations,1,NaN
1604,King's Lynn and West Norfolk,16-24,No qualifications,Associate professional and technical occupations,14,NaN
1605,King's Lynn and West Norfolk,16-24,No qualifications,Administrative and secretarial occupations,21,NaN
1606,King's Lynn and West Norfolk,16-24,No qualifications,Skilled trades occupations,94,NaN
...,...,...,...,...,...,...
55552,"Cornwall,Isles of Scilly",50-64,Apprenticeships and other qualifications,Skilled trades occupations,3326,NaN
55553,"Cornwall,Isles of Scilly",50-64,Apprenticeships and other qualifications,"Caring, leisure and other service occupations",652,NaN
55554,"Cornwall,Isles of Scilly",50-64,Apprenticeships and other qualifications,Sales and customer service occupations,458,NaN
55555,"Cornwall,Isles of Scilly",50-64,Apprenticeships and other qualifications,"Process, plant and machine operatives",1343,NaN
55556,"Cornwall,Isles of Scilly",50-64,Apprenticeships and other qualifications,Elementary occupations,915,NaN

In [56]:
set(null["Local district"])

{'Cornwall,Isles of Scilly',
 "King's Lynn and West Norfolk",
 'Westminster,City of London'}

In [57]:
#replace Folkestone and Hythe to Shepway
df4['Local district'] = df4['Local district'].str.replace('Cornwall,Isles of Scilly','Cornwall')
df4['Local district'] = df4['Local district'].str.replace('Westminster,City of London','Westminster')
df4['Local district'] = df4['Local district'].str.replace("King's Lynn and West Norfolk","King’s Lynn and West Norfolk")

In [58]:
#create region using region dictionary mapping Local district
df4["Region"] = df4["Local district"].map(region)

In [59]:
#check for any null values
null = df4[df4.isnull().any(axis=1)]
null

Empty DataFrame
Columns: [Local district, Age, Qualification, Occupation, Total people with occupations, Region]
Index: []

In [60]:
#rearrange the columns
df4 = df4[["Local district", "Region", "Age", "Qualification", "Occupation", "Total people with occupations"]]

In [61]:
#save as excel file
os.chdir(transformed_data_path)
with pd.ExcelWriter("occupation ethnic age gender.xlsx", mode='a', engine="openpyxl") as writer:
    df4.to_excel(writer, sheet_name='occ qual age')
os.chdir(pwd)